---
title: "Merge LA refinery data sets"
author: "Jerry Wu"
date: "5/1/2023"
output:
  html_document:
    df_print: paged
abstract: ''
subtitle: ''
---

```{r setup, include=FALSE}
library(tidyverse)
library(mgcv)
```

```{r}
# load data sets
full_data <- tibble()
names <- c(ws = 'windSpeed', wd = 'windDirection', H2S = 'Value')
for (file in list.files('data/raw_csv')){
  new_data <- read.csv(paste0('data/raw_csv/', file)) %>% rename(any_of(names))
  print(sum(is.na(new_data$H2S)))
  full_data <- bind_rows(full_data, new_data)
}
```

```{r}
full_data <- full_data %>% mutate(DateTime = as.POSIXct(DateTime, format="%m/%d/%Y %H:%M", tz = 'UTC'),
                                  Date.Time = as.POSIXct(Date.Time, format="%m/%d/%Y %H:%M", tz = 'UTC'),
                                  Date.Time.First = as.POSIXct(Date.Time.First, format="%m/%d/%Y %H:%M", tz = 'UTC'))
full_data <- full_data %>% 
  mutate(day = format(DateTime, "%Y-%m-%d")) %>%
  mutate(day = if_else(is.na(day), format(Date.Time, "%Y-%m-%d"), day)) %>%
  mutate(day = if_else(is.na(day), format(Date.Time.First, "%Y-%m-%d"), day)) %>%
  mutate(day = as.POSIXct(day, format="%Y-%m-%d")) %>%
  mutate(yearmonth = format(day, "%Y-%m")) %>%
  mutate(year = format(day, "%Y")) %>%
  mutate(month = format(day, "%m"))
```

```{r}
glimpse(full_data)
```

```{r}
summary(full_data)
```
Some concerns for the data include:
For TorranceAir_H2SWind, there are actually three sites, but only one site contains ws/wd information
What's the difference between DateTime and Date/Time?
What's the difference between Date/Time and Date/Time.First? The latter is present in FirstMethodist

# Compute Daily Max H2S
```{r}
H2S_dm <- full_data %>%
  group_by(day, Monitor) %>%
  summarise(H2S_daily_max = max(H2S, na.rm = TRUE)) %>%
  mutate(H2S_daily_max = if_else(H2S_daily_max == -Inf, NA, H2S_daily_max))

full_data <- full_data %>%
  left_join(H2S_dm, by = c('day', 'Monitor'))
```

```{r}
H2S_ma <- H2S_dm %>%
  mutate(yearmonth = format(day, "%Y-%m")) %>%
  group_by(yearmonth, Monitor) %>%
  summarise(H2S_monthly_average = mean(H2S_daily_max, na.rm = TRUE))

full_data <- full_data %>%
  left_join(H2S_ma, by = c('yearmonth', 'Monitor'))
```

```{r}
full_data <- full_data %>%
  mutate(wd_sec = case_when(0 <= wd & wd < 90 ~ 'Q1',
                            90 <= wd & wd < 180 ~ 'Q2',
                            180 <= wd & wd < 270 ~ 'Q3',
                            270 <= wd & wd <= 360 ~ 'Q4'))
```

```{r}
saveRDS(full_data, 'data/full_data.rds')
```

