---
title: "Pirate Bay Weather"
author: "Jerry Wu"
date: "2023-11-01"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
library(tidyverse)
library(httr)
library(jsonlite)
library(sf)
```

```{r}
api <- '4Q7hFEmsDjk3orhrP46zKtmQ0BMGYw9s'
```

```{r}
# get dates for disaser and normal periods
dates <- seq(as.POSIXct('2021-10-01', tz = 'America/Los_Angeles'), as.POSIXct('2021-10-31', tz = 'America/Los_Angeles'),"days")
disaster_dates <- tibble(day = dates, unix = as.numeric(dates))

dates <- seq(as.POSIXct('2022-10-01', tz = 'America/Los_Angeles'), as.POSIXct('2022-10-31', tz = 'America/Los_Angeles'),"days")
normal_dates <- tibble(day = dates, unix = as.numeric(dates))
```

```{r}
# get grid points
grd_data <- readRDS('rfiles/grd_data_disaster.rds')
grd_data <- grd_data %>%
  select(mon_utm_x, mon_utm_y) %>%
  distinct() %>%
  mutate(x = mon_utm_x, y = mon_utm_y) %>%
  st_as_sf(coords = c('x', 'y')) %>%
  st_set_crs("+proj=utm +zone=11 ellps=WGS84") %>%
  st_transform("+proj=longlat +datum=WGS84") %>%
  mutate(lon = sf::st_coordinates(.)[,1],
         lat = sf::st_coordinates(.)[,2]) %>%
  st_drop_geometry()

point_date <- rbind(disaster_dates, normal_dates) %>%
  cross_join(grd_data)
```

```{r}
# Sample request
start_time <- Sys.time()
get_url <- sprintf('https://timemachine.pirateweather.net/forecast/%s/%s,%s,%s?exclude=minutely,hourly',
                   api, point_date$lat[80000], point_date$lon[80000], '1604270546')

res = GET(get_url)
end_time <- Sys.time()
end_time - start_time
data = fromJSON(rawToChar(res$content))
names(data)
```

```{r}
data$currently
```

```{r}
data$daily$data
```

```{r}
result <- tibble(date = data$daily$data$time,
                 avg_temp = mean(data$daily$data$temperatureHigh, data$daily$data$temperatureLow),
                 wd = data$daily$data$windBearing,
                 ws = data$daily$data$windSpeed,
                 precip = data$daily$data$precipAccumulation,
                 dewpoint = data$daily$data$dewPoint) %>%
  mutate(humidity = 100 * (exp((17.625 * (dewpoint - 32) * (5/9)) / (243.04 + (dewpoint - 32) * (5/9))) / exp((17.625 * (avg_temp - 32) * (5/9)) / (243.04 + (avg_temp - 32) * (5/9)))))
```