---
title: "Zipcode prediction"
author: "Jerry Wu"
date: "2024-03-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(httr)
library(jsonlite)
library(sf)
library(circular)
select <- dplyr::select
```

# Load in data
```{r}
full_monitor_data <- readRDS('site_data_for_weather.rds')
```
```{r}
# get unique day monitor pairs and lat/lon for weather fetching
distinct_day_monitor <- full_monitor_data %>%
  select(c(Monitor, day, lat, lon)) %>%
  distinct()

monitor_date_range <- distinct_day_monitor %>%
  group_by(Monitor, lat, lon) %>%
  summarise(start_date = min(day),
            end_date = max(day))
```


```{r}
# Code to fetch weather data
daily_result <- tibble(Monitor = character(),
                       latitude = numeric(),
                       longitude = numeric(),
                       day = numeric(),
                       daily_temp = numeric(),
                       daily_hum = numeric(),
                       daily_precip = numeric(),
                       daily_ws = numeric(),
                       daily_wd = numeric())

hourly_result <- tibble(Monitor = character(),
                        latitude = numeric(),
                        longitude = numeric(),
                        hourly = numeric(),
                        hourly_temp = numeric(),
                        hourly_hum = numeric(),
                        hourly_precip = numeric(),
                        hourly_ws = numeric(),
                        hourly_wd = numeric())

# loop through rows
for (i in 1:nrow(monitor_date_range)){
  
  get_url <- str_glue("https://archive-api.open-meteo.com/v1/archive?latitude={lat}",
                      "&longitude={lon}&start_date={start_date}&end_date={end_date}",
                      "&hourly=temperature_2m,relative_humidity_2m,precipitation,",
                      "wind_speed_10m,wind_direction_10m&temperature_unit=fahrenheit",
                      "&wind_speed_unit=mph&precipitation_unit=inch&timezone=America%2FLos_Angeles",
                      lat = monitor_date_range$lat[i],
                      lon = monitor_date_range$lon[i],
                      start_date = monitor_date_range$start_date[i],
                      end_date = monitor_date_range$end_date[i])

  res = GET(get_url)
  data = fromJSON(rawToChar(res$content))
  if (!(is.null(try(data$error)))){
    ith_hourly_result <- tibble(Monitor = monitor_date_range$Monitor[i],
                                latitude = monitor_date_range$lat[i],
                                longitude = monitor_date_range$lon[i],
                                hourly = NA,
                                hourly_temp = NA,
                                hourly_hum = NA,
                                hourly_precip = NA,
                                hourly_ws = NA,
                                hourly_wd = NA)
    
    ith_daily_result <- tibble(latitude = monitor_date_range$lat[i],
                               longitude = monitor_date_range$lon[i],
                               day = NA,
                               daily_temp = NA,
                               daily_hum = NA,
                               daily_precip = NA,
                               daily_ws = NA,
                               daily_wd = NA)
  }
  else {
    # add to hourly result table
    ith_hourly_result <- tibble(Monitor = monitor_date_range$Monitor[i],
                            latitude = monitor_date_range$lat[i],
                            longitude = monitor_date_range$lon[i],
                            hourly = data$hourly$time,
                            hourly_temp = data$hourly$temperature_2m,
                            hourly_hum = data$hourly$relative_humidity_2m,
                            hourly_precip = data$hourly$precipitation,
                            hourly_ws = data$hourly$wind_speed_10m,
                            hourly_wd = data$hourly$wind_direction_10m)
    
    # group by day and compute daily results
    ith_daily_result <- ith_hourly_result %>%
      mutate(date = as.POSIXct(hourly)) %>%
      mutate(day = format(date, "%Y-%m-%d"))
    
    ith_daily_result$hourly_wd <- as.numeric(ith_daily_result$hourly_wd)

    ith_daily_result <- ith_daily_result %>%
      group_by(Monitor, latitude, longitude, day) %>%
      summarise(daily_temp = mean(hourly_temp, na.rm = T),
                daily_hum = mean(hourly_hum, na.rm = T),
                daily_precip = sum(hourly_precip, na.rm = T),
                daily_ws = mean(hourly_ws, na.rm = T),
                daily_wd = as.numeric(mean(circular(hourly_wd, units = 'degrees'), na.rm=TRUE)),
                .groups = 'drop')
    
    ith_daily_result <- ith_daily_result %>%
      mutate(daily_wd = if_else(daily_wd < 0, daily_wd + 360, daily_wd))
  }

  hourly_result <- rbind(hourly_result, ith_hourly_result)
  
  daily_result <- rbind(daily_result, ith_daily_result)
  
  print(sprintf("Row %s completed", i))
}

saveRDS(daily_result, 'monitor_daily_weather.rds')
saveRDS(hourly_result, 'monitor_hourly_weather.rds')
```

