---
title: "Zipcode Grid Data Prepare"
author: "Jerry Wu"
date: "2024-03-25"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
library(tidyverse)
library(sf)
library(stars)
library(ggspatial)
library(KernSmooth)
library(rgdal)
library(mgcv)
library(raster)
library(caret)
library(leaflet)
library(htmlwidgets)
library(fontawesome) 
library(units)
library(lwgeom)
library(magick)
library(httr)
library(jsonlite)
library(circular)
library(ggmap)
library(mapview)
library(leafem)
select <- dplyr::select
```

# Get Zipcodes
```{r}
patient_zip <- read_csv('lacounty_EDpatients_ZIPcodes.csv')

patient_zip <- patient_zip[ ,2:3] %>% distinct()

# daily_full <- readRDS('../../data/daily_full.rds')

CRS_UTM <- CRS("+proj=utm +zone=11 ellps=WGS84")

CRS_LL <- CRS("+proj=longlat +datum=WGS84")

# mon_location <- daily_full %>%
#   select(Monitor, mon_utm_x, mon_utm_y) %>%
#   distinct() %>%
#   st_as_sf(coords = c('mon_utm_x', 'mon_utm_y')) %>%
#   st_set_crs(CRS_UTM)

ca_zip <- read_sf('../../shapefiles/CA_Zipcode.shp')
ca_zip_point <- read_sf('../../shapefiles/CA_Zipcode_points.shp')


patient_zipcode_boundaries <- ca_zip[ca_zip$ZIP_CODE %in% patient_zip$zipcode, ]
patient_zipcode_points <- ca_zip_point[ca_zip_point$ZIP_CODE %in% patient_zip$zipcode, ]

# la_county <- read_sf('../../shapefiles/Zip_Codes_(LA_County)/Zip_Codes_(LA_County).shp')
# 
# la_county_trans <- st_transform(la_county, CRS_UTM)      # apply transformation to polygons sf
# 
# # intersect and extract state name
# mon_location$county <- apply(st_intersects(la_county_trans, mon_location, sparse = FALSE), 2, 
#                              function(col) { 
#                                la_county_trans[which(col), ]$ZIPCODE
#                              })
# # These are the counties with a Monitor
# la_county_present <- la_county_trans[la_county_trans$ZIPCODE %in% unique(mon_location$county), ]
# # Add some more
# additional_zip <- c(90278, 90260, 90501, 90505, 90710, 90746, 90248, 90806, 
#                     90807, 90247, 90710, 90502, 90717, 90250, 90249, 90506, 
#                     90747, 90755, 90731, 90732, 90802, 90277, 90254, 90261)
# la_county_full <- rbind(la_county_present, 
#                         la_county_trans[la_county_trans$ZIPCODE %in% additional_zip, ])
# 
# remove(la_county_present, mon_location, daily_full)

zipcode_boundaries_popup <- paste0("<strong>Zipcode: </strong>", patient_zipcode_boundaries$ZIP_CODE, "<br>",
                        "<strong>Population: </strong>", patient_zipcode_boundaries$POPULATION)

zipcode_points_popup <- paste0("<strong>Zipcode: </strong>", patient_zipcode_points$ZIP_CODE, "<br>",
                        "<strong>Population: </strong>", patient_zipcode_points$POPULATION)

register_stadiamaps("2960e34d-9997-48db-abeb-360be74fc3f5", write = TRUE)

zipcode_map <- leaflet() %>% 
      addProviderTiles(providers$MtbMap) %>%
              addProviderTiles(providers$Stadia.StamenTerrainBackground,
                               options = providerTileOptions(opacity = 0.9, api_key = "2960e34d-9997-48db-abeb-360be74fc3f5")) %>%
              addProviderTiles(providers$Stadia.StamenTonerLines,
                options = providerTileOptions(opacity = 0.25, api_key = "2960e34d-9997-48db-abeb-360be74fc3f5")) %>%
              addProviderTiles(providers$Stadia.StamenTonerLabels,
                               options=providerTileOptions(api_key = "2960e34d-9997-48db-abeb-360be74fc3f5")) %>%
      addPolygons(data = patient_zipcode_boundaries,
                  fillOpacity = 0.5, 
                  weight = 2, 
                  color = "#808080",
                  fillColor = '#C0C0C0',
                  popup = zipcode_boundaries_popup) %>%
      addCircleMarkers(data = patient_zipcode_points,
                  fillOpacity = 0.9,
                  radius = 2,
                  weight = 1, 
                  color = "#DC143C",
                  popup = zipcode_points_popup)
zipcode_map
# saveWidget(zipcode_map, file="zipcode_map.html")
# mapshot(zipcode_map, file = "zipcode_map.png")
```

```{r}
# Subset Zip Code boundaries
patient_zipcode_points_cropped <- patient_zipcode_points %>%
  st_crop(xmin = -118.46, xmax = -118.14, ymin = 33.7, ymax = 33.99)

patient_zipcode_boundaries_cropped <- patient_zipcode_boundaries %>%
    filter(ZIP_CODE %in% patient_zipcode_points_cropped$ZIP_CODE)

zipcode_boundaries_popup <- paste0("<strong>Zipcode: </strong>", patient_zipcode_boundaries_cropped$ZIP_CODE, "<br>",
                        "<strong>Population: </strong>", patient_zipcode_boundaries_cropped$POPULATION)

zipcode_points_popup <- paste0("<strong>Zipcode: </strong>", patient_zipcode_points_cropped$ZIP_CODE, "<br>",
                        "<strong>Population: </strong>", patient_zipcode_points_cropped$POPULATION)

leaflet() %>% 
      addProviderTiles(providers$MtbMap) %>%
              addProviderTiles(providers$Stadia.StamenTerrainBackground,
                               options = providerTileOptions(opacity = 0.9, api_key = "2960e34d-9997-48db-abeb-360be74fc3f5")) %>%
              addProviderTiles(providers$Stadia.StamenTonerLines,
                options = providerTileOptions(opacity = 0.25, api_key = "2960e34d-9997-48db-abeb-360be74fc3f5")) %>%
              addProviderTiles(providers$Stadia.StamenTonerLabels,
                               options=providerTileOptions(api_key = "2960e34d-9997-48db-abeb-360be74fc3f5")) %>%
      addPolygons(data = patient_zipcode_boundaries_cropped,
                  fillOpacity = 0.5, 
                  weight = 2, 
                  color = "#808080",
                  fillColor = '#C0C0C0',
                  popup = zipcode_boundaries_popup) %>%
       addCircleMarkers(data = patient_zipcode_points_cropped,
                  fillOpacity = 0.9,
                  radius = 2,
                  weight = 1, 
                  color = "#DC143C",
                  popup = zipcode_points_popup)
```


# Set up grid
## Using the stars package to counties
```{r}
# Get the grids for the zip codes as a whole
patient_zipcode_boundaries_cropped <- st_transform(patient_zipcode_boundaries_cropped, CRS_UTM)

zipcode_grid_full <- st_bbox(patient_zipcode_boundaries_cropped) %>%
                  st_as_stars(dx = 500)

zipcode_grid_full <- zipcode_grid_full %>%
  mutate(utm_x = sf::st_coordinates(.)[,1],
         utm_y = sf::st_coordinates(.)[,2])

zipcode_grid_full <- zipcode_grid_full %>%
  st_transform("+proj=longlat +datum=WGS84") %>%
  mutate(lon = sf::st_coordinates(.)[,1],
         lat = sf::st_coordinates(.)[,2])

zipcode_grid <- st_bbox(patient_zipcode_boundaries_cropped) %>%
                  st_as_stars(dx = 500) %>%
                  st_crop(patient_zipcode_boundaries_cropped, as_points = FALSE)

zipcode_grid <- zipcode_grid %>%
  mutate(utm_x = sf::st_coordinates(.)[,1],
         utm_y = sf::st_coordinates(.)[,2])

zipcode_grid <- zipcode_grid %>%
  st_transform("+proj=longlat +datum=WGS84") %>%
  mutate(lon = sf::st_coordinates(.)[,1],
         lat = sf::st_coordinates(.)[,2])

zipcode_grid_df <- as.data.frame(zipcode_grid) %>% filter(values == 0)
print(paste0('Number of cells at 500m resolution: ', nrow(zipcode_grid_df)))
```

```{r}
zipcode_grid_full$col <- 1:(dim(zipcode_grid_full)[[1]] * dim(zipcode_grid_full)[[2]])
plot(zipcode_grid_full['col',,], reset = FALSE)
image(zipcode_grid, add = TRUE, col = sf.colors())
plot(patient_zipcode_boundaries_cropped %>% 
       st_transform(CRS_LL) %>%
       select(geometry), add = TRUE, border = 'green', lwd = 2)
```


```{r}
write_csv(zipcode_grid_df, 'zipcode_grid_df.csv')
```

```{r}
patient_zipcode_boundaries_ll <- patient_zipcode_boundaries_cropped %>%
  st_transform(CRS_LL)

zipcode_grid_raster <- rasterFromXYZ(zipcode_grid_df %>% select(utm_x, utm_y, 1))
crs(zipcode_grid_raster) <- CRS_UTM
zipcode_grid_raster_ll <- projectRaster(zipcode_grid_raster, crs = CRS_LL)

zipcode_grid_raster_subset <- rasterFromXYZ(zipcode_grid_df %>% select(utm_x, utm_y, 1) %>% head(5))
crs(zipcode_grid_raster_subset) <- CRS_UTM
zipcode_grid_raster_subset_ll <- projectRaster(zipcode_grid_raster_subset, crs = CRS_LL)

zipcode_grid_raster
```
 


 
 