---
title: "Zipcode prediction"
author: "Jerry Wu"
date: "2024-03-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(httr)
library(jsonlite)
library(sf)
library(circular)
```

# Load in data
```{r}
zipcode_grid_df_home <- read_csv('zipcode_grid_df_home.csv')
zipcode_grid_fetched_home <- read_csv('zipcode_grid_fetched_home.csv')
```

```{r}
# Code to fetch weather data
# For first time
zipcode_grid_fetched_home <- tibble(lon = numeric(), lat = numeric())
 
zipcode_grid_unfetched_home <- zipcode_grid_df_home %>%
  anti_join(zipcode_grid_fetched_home, join_by(lon, lat))

hourly_result <- tibble(latitude = numeric(),
                 longitude = numeric(),
                 hourly = numeric(),
                 hourly_temp = numeric(),
                 hourly_hum = numeric(),
                 hourly_precip = numeric(),
                 hourly_ws = numeric(),
                 hourly_wd = numeric())
counter <- 0
start_time <- Sys.time()
for (i in 1:nrow(zipcode_grid_unfetched_home)) {
  if (counter == 150) {
    break
  }
  reset <- FALSE
  # In order to follow the 600 calls per minute restriction from open-meteo
  if (counter != 0 && counter %% 9 == 0) {
    end_time <- Sys.time()
    sec_until_60s <- 60 - (as.numeric(end_time) - as.numeric(start_time))
    print(paste0('Completed ', counter, ' coordinates'))
    print(paste0('Waiting ', sec_until_60s, ' seconds'))
    Sys.sleep(sec_until_60s + 3) # give 3s buffer
    reset <- TRUE
  }

  # In order to follow the 5000 calls per hour restriction from open-meteo
  if (counter != 0 && counter %% 55 == 0) {
    end_time <- Sys.time()
    sec_until_60m <- 3600 - (as.numeric(end_time) - as.numeric(start_time))
    print(paste0('Completed ', counter, ' coordinates'))
    print(paste0('Waiting ', sec_until_60m, ' seconds'))
    Sys.sleep(sec_until_60m + 30) # give 30s buffer
    reset <- TRUE
  }

  if (reset == T) {
    start_time <- Sys.time()
  }

  counter <- counter + 1


    get_url <- sprintf("https://archive-api.open-meteo.com/v1/archive?latitude=%s&longitude=%s&start_date=2018-01-01&end_date=2022-12-31&hourly=temperature_2m,relative_humidity_2m,precipitation,wind_speed_10m,wind_direction_10m&temperature_unit=fahrenheit&wind_speed_unit=mph&precipitation_unit=inch&timezone=America%%2FLos_Angeles",
                       zipcode_grid_unfetched_home$lat[i], zipcode_grid_unfetched_home$lon[i])
  res = GET(get_url)
  data = fromJSON(rawToChar(res$content))
  hourly_result <- rbind(hourly_result,
                         tibble(latitude = zipcode_grid_unfetched_home$lat[i],
                                longitude = zipcode_grid_unfetched_home$lon[i],
                                elevation = data$elevation,
                                hourly = data$hourly$time,
                                hourly_temp = data$hourly$temperature_2m,
                                hourly_hum = data$hourly$relative_humidity_2m,
                                hourly_precip = data$hourly$precipitation,
                                hourly_ws = data$hourly$wind_speed_10m,
                                hourly_wd = data$hourly$wind_direction_10m))
}


result <- rbind(zipcode_grid_fetched_home,
                hourly_result)
write_csv(hourly_result, 'zipcode_grd_fetched_home.csv')
```

```{r}
# hourly_result <- read_csv('top_3_blk_hourly_with_meteo.csv')
# 
# daily_result <- hourly_result %>%
#   mutate(date = as.POSIXct(hourly)) %>%
#   mutate(day = format(date, "%Y-%m-%d"))
# 
# remove(hourly_result)
# 
# daily_result$hourly_wd <- as.numeric(daily_result$hourly_wd)
# 
# daily_result <- daily_result %>%
#   group_by(latitude, longitude, day) %>%
#   summarise(daily_temp = mean(hourly_temp, na.rm = T),
#             daily_hum = mean(hourly_hum, na.rm = T),
#             daily_precip = sum(hourly_precip, na.rm = T),
#             daily_ws = mean(hourly_ws, na.rm = T),
#             daily_wd = as.numeric(mean(circular(hourly_wd, units = 'degrees'), na.rm=TRUE)))
# 
# daily_result <- daily_result %>%
#   ungroup() %>%
#   mutate(day = as.POSIXct(day),
#          daily_wd = if_else(daily_wd < 0, daily_wd + 360, daily_wd),
#          yearmonth = format(day, "%Y-%m"),
#          year = format(day, "%Y"),
#          month = format(day, "%m"),
#          weekday = relevel(factor(wday(daily_result$day, label=TRUE), ordered = FALSE), ref = "Sun"))
# 
# write_csv(daily_result, 'top_3_blk_daily_with_meteo.csv')
```

```{r}
top_3_blk_daily_with_meteo <- read_csv('top_3_blk_daily_with_meteo.csv')
# 
# # Compare to pirate weather
# api <- '4Q7hFEmsDjk3orhrP46zKtmQ0BMGYw9s'
# 
# top_3_blk_with_date <- top_3_blk %>%
#   cross_join(tibble(day = seq(as.POSIXct('2018-01-01', tz = 'America/Los_Angeles'), as.POSIXct('2022-12-31', tz = 'America/Los_Angeles'),"days"))) %>%
#   mutate(unix = as.numeric(day))
# 
# set.seed(123)
# top_3_blk_sample <- top_3_blk_with_date %>%
#   sample_n(200)
# 
# top_3_blk_sample_temp <- read_csv('top_3_blk_sample.csv')
# 
# result_tibble1 <- tibble(rowid = numeric(),
#                         avg_temp = numeric(),
#                         wd_avg = numeric(),
#                         ws_avg = numeric(),
#                         precip = numeric(),
#                         dewpoint = numeric(),
#                         hum = numeric())
# # loop through rows
# for (i in 1:nrow(top_3_blk_sample)){
#   get_url <- sprintf('https://timemachine.pirateweather.net/forecast/%s/%s,%s,%s?exclude=minutely,hourly',
#                    api, top_3_blk_sample$INTPTLAT[i], top_3_blk_sample$INTPTLON[i], top_3_blk_sample$unix[i])
#   res = GET(get_url)
#   data = fromJSON(rawToChar(res$content))
#   if (typeof(data) == 'character') {
#     result_tibble1 <- rbind(result_tibble1, tibble(rowid = i, avg_temp = NA, wd_avg = NA, ws_avg = NA, precip = NA, dewpoint = NA, hum = NA))
#   } else if (is.null(data$daily)) {
#     result_tibble1 <- rbind(result_tibble1, tibble(rowid = i, avg_temp = NA, wd_avg = NA, ws_avg = NA, precip = NA, dewpoint = NA, hum = NA))
#   } else {
#     result_tibble1 <- rbind(result_tibble1, tibble(rowid = i,
#                                                  avg_temp = mean(data$daily$data$temperatureHigh, data$daily$data$temperatureLow),
#                                                  wd_avg = data$daily$data$windBearing,
#                                                  ws_avg = data$daily$data$windSpeed,
#                                                  precip = data$daily$data$precipAccumulation,
#                                                  dewpoint = data$daily$data$dewPoint) %>%
#                                               mutate(hum = 100 * (exp((17.625 * (dewpoint - 32) * (5/9)) / (243.04 + (dewpoint - 32) * (5/9)))
#                                                                        / exp((17.625 * (avg_temp - 32) * (5/9)) / (243.04 + (avg_temp - 32) * (5/9))))))
#   }
#   print(sprintf("Row %s completed", i))
#   if (i %% 10 == 0) {write_csv(cbind(top_3_blk_sample[1:i, ], result_tibble1), 'top_3_blk_sample_temp.csv')}
# }
# 
# top_3_blk_sample <- cbind(top_3_blk_sample, result_tibble1)
# 
# write_csv(top_3_blk_sample, 'top_3_blk_sample_result.csv')
```

```{r}
# comparisons
top_3_blk_sample_result <- read_csv('top_3_blk_sample_result.csv')

top_3_blk_sample_result <- top_3_blk_sample_result %>%
  mutate(day = format(day, "%Y-%m-%d"))

comp <- top_3_blk_sample_result %>% 
  left_join(top_3_blk_daily_with_meteo %>% mutate(day = format(day, "%Y-%m-%d")), join_by(INTPTLAT == latitude, INTPTLON == longitude, day)) %>%
  mutate(temp_diff = avg_temp - daily_temp,
         wd_diff = wd_avg - daily_wd,
         ws_diff = ws_avg - daily_ws,
         precip_diff = precip - daily_precip,
         hum_diff = hum - daily_hum)

comp %>% 
  select(temp_diff, wd_diff, ws_diff, precip_diff, hum_diff) %>%
  summary()
```

