---
title: "Zipcode Prediction"
author: "Jerry Wu"
date: "2023-12-12"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
library(tidyverse)
library(sf)
library(stars)
library(ggspatial)
library(KernSmooth)
library(rgdal)
library(mgcv)
library(raster)
library(caret)
library(leaflet)
library(htmlwidgets)
library(fontawesome) 
library(units)
library(lwgeom)
library(magick)
select <- dplyr::select
```

```{r}
# load in data
top_3_blk_daily_with_meteo <- read_csv('top_3_blk_daily_with_meteo.csv')

# load in model
fit.xgb_da_log_h2s_dis_ind <- readRDS('../../rfiles/fit.xgb_da_log_h2s_dis_ind.rds')
```

```{r}
CRS_UTM <- CRS("+proj=utm +zone=11 ellps=WGS84")
CRS_LL <- CRS("+proj=longlat +datum=WGS84")
# Helper Functions 
get_sf_loc <- function(utm_x, utm_y) {
  sf_loc <- st_as_sf(tibble(utm_x = utm_x, utm_y = utm_y), 
                     coords = c('utm_x', 'utm_y')) %>%
    st_set_crs(CRS_UTM)
  return(sf_loc)
}

get_ll_loc <- function(utm_x, utm_y) {
  ll_loc <- st_as_sf(tibble(utm_x = utm_x, utm_y = utm_y), 
                     coords = c('utm_x', 'utm_y')) %>%
    st_set_crs(CRS_UTM) %>%
    st_transform(CRS_LL)
  return(ll_loc)
}

# compute missing variables
# WRP Data
la_wrp <- read_sf('../../shapefiles/LA_WRP.shp', layer = 'LA_WRP')

# Convert both water treatment plants and monitor coordinates to UTM
la_wrp <- st_transform(la_wrp, CRS_UTM)

get_dist_wrp <- function(location) {
  return(tibble(dist_wrp = apply(st_distance(location, la_wrp), 1, min),
                capacity = la_wrp$cpcty_m[st_nearest_feature(location, la_wrp)]))
}

get_angle_wrp <- function(location) {
  angles <- tibble(location, la_wrp$geometry[st_nearest_feature(location, la_wrp)]) %>%
                pivot_longer(cols = everything()) %>% 
                pull(value) %>% # extract coordinates only
                st_transform(4326) %>% # convert to lat/lon for function below
                st_geod_azimuth() %>%
                set_units('degrees') %>% # convert to degrees
                drop_units()
  angles <- angles[c(T, F)] # keep only odd index, valid pairs
  angles <- if_else(angles < 0, angles + 360, angles)
  return(angles)
}

# Get MinDist to Refinery
st_read('../../shapefiles/Petroleum_Refinery.shp')
refineries <- read_sf('../../shapefiles/Petroleum_Refinery.shp', layer = 'Petroleum_Refinery')
refineries <- refineries %>%
  select(Company, Site, Latitude, Longitude) %>%
  mutate(refinery = case_when(Site == 'Carson' ~ 'Marathon (Carson)',
                              Site == 'El Segundo' ~ 'Chevron El Segundo',
                              Site == 'Wilmington Asphalt Plant' ~ 'Valero Refinery',
                              Site == 'Wilmington Refinery' ~ 'Marathon (Wilmington)',
                              Site == 'Torrance' ~ 'Torrance Refinery',
                              Site == 'Wilmington' ~ 'Phillips 66 (Wilmington)')) %>%
  st_transform(CRS_UTM)

get_dist_ref <- function(location) {
  return(apply(st_distance(location, refineries), 1, min))
}

get_angle_ref <- function(location) {
  angles <- tibble(location, refineries$geometry[st_nearest_feature(location, refineries)]) %>%
                pivot_longer(cols = everything()) %>% 
                pull(value) %>% # extract coordinates only
                st_transform(4326) %>% # convert to lat/lon for function below
                st_geod_azimuth() %>%
                set_units('degrees') %>% # convert to degrees
                drop_units()
  angles <- angles[c(T, F)] # keep only odd index, valid pairs
  angles <- if_else(angles < 0, angles + 360, angles)
  return(angles)
}

# Get production data
well_prod <- read_csv('../../data/LA well prod Dec2023 Well Monthly Production.CSV', show_col_types = FALSE)
full_well_info <- read_csv('../../data/well_active_inactive_prod_since_2000.CSV', show_col_types = FALSE)
active_well_info <- read_csv('../../data/LA well prod Dec2023 Well Headers.CSV', show_col_types = FALSE)

inactive_well_info <- anti_join(full_well_info, active_well_info, join_by(API14)) %>%
  rename(lon = `Surface Hole Longitude (WGS84)`,
         lat = `Surface Hole Latitude (WGS84)`) %>%
  select(`API14`, lon, lat) %>%
  distinct() %>%
  st_as_sf(coords = c('lon', 'lat')) %>%
  st_set_crs(4326) %>%
  st_transform(CRS_UTM)

well_prod <- well_prod %>%
  left_join(active_well_info, join_by(`API/UWI` == API14))

well_prod <- well_prod %>%
  select(`API/UWI`, `Monthly Production Date`, `Monthly Oil`, `Monthly Gas`,
         `Monthly Water`, `Monthly BOE`, Days, `Operator Company Name.x`,
         `Production Type.x`, `Well Status.x`, `Drill Type`,
         `Surface Hole Latitude (WGS84)`, `Surface Hole Longitude (WGS84)`) %>%
  rename(lon = `Surface Hole Longitude (WGS84)`,
         lat = `Surface Hole Latitude (WGS84)`)

# project distinct well locations to UTM
active_well_location <- well_prod %>%
  select(`API/UWI`, lon, lat) %>%
  distinct() %>%
  st_as_sf(coords = c('lon', 'lat')) %>%
  st_set_crs(4326) %>%
  st_transform(CRS_UTM)

get_well_prod <- function(api, month) {
  # if month is later than a certain month, return NA
  if (month > max(well_prod$`Monthly Production Date`) + 31){
    return(tibble(active_2km = NA,
                  monthly_oil_2km = NA,
                  monthly_gas_2km = NA))
  }
  
  loc_well_prod <- well_prod %>%
    filter(`API/UWI` %in% unlist(api))
  
  loc_well_prod <- loc_well_prod %>%
    filter(`Monthly Production Date` == month) %>%
    group_by(`Monthly Production Date`) %>%
    summarise(active_2km = n(),
              monthly_oil_2km = sum(`Monthly Oil`, na.rm = TRUE),
              monthly_gas_2km = sum(`Monthly Gas`, na.rm = TRUE))
  
  # consider the case when there is no well prod data
  if (nrow(loc_well_prod) == 0) {
    return(tibble(active_2km = 0,
                  monthly_oil_2km = 0,
                  monthly_gas_2km = 0))
  }
  return(loc_well_prod)
}

get_well_inactive <- function(location) {
  # get inactive wells within 2km
  inactive_well_api <- drop_units(st_distance(location, inactive_well_info))
  inactive_well_api <- inactive_well_info[which(inactive_well_api <= 2000), ] %>% st_drop_geometry()
  return(nrow(inactive_well_api))
}

# Get elevation
elevation <- raster('../../shapefiles/N33W119.hgt')

get_elevation <- function(location_ll) {
  return(raster::extract(elevation, location_ll))
}

# Get EVI
evi <- raster('../../shapefiles/MOD13Q1.061__250m_16_days_EVI_doy2023145_aid0001_2.tif')

evi <- projectRaster(evi, crs = CRS_UTM)
# fill NA pixels
dist <- distance(evi)  

direct <- direction(evi, from=FALSE)

evi_na <- is.na(evi) 

na_x <- init(evi_na, 'x')
na_y <- init(evi_na, 'y')

co_x <- na_x + dist * sin(direct)
co_y <- na_y + dist * cos(direct)

co <- cbind(co_x[], co_y[]) 

NAVals <- raster::extract(evi, co, method='simple') 
evi_NAVals <- evi # initiate new raster
evi_NAVals[] <- NAVals # store values in raster

evi_filled <- cover(x=evi, y = evi_NAVals)

evi_filled <- projectRaster(evi_filled, crs = "+proj=longlat +datum=WGS84")

get_evi <- function(location){
  return(raster::extract(evi_filled, location) * 0.0001)
}

# Get Number of Odor Complaints
odor <- read_csv('../../data/odorcomplaintdata_2018_2023.csv')
top_3_blk_wo_meteo <- read_csv('top_3_blk_without_meteo.csv')

odor <- odor %>%
  filter(zip %in% top_3_blk_wo_meteo$ZCTAA)

odor$date <- as.character(odor$date)

get_odor <- function(zipcode, day) {
  odor <- odor %>% filter(zip == zipcode & date == format(day, '%Y-%m-%d'))
  if (nrow(odor) == 0) {
    return(0)
  } else {
    return(odor$num_odor_complaints)
  }
}


# Distance to Dominguez Channel
# Read in the shape file, it already has a CRS
st_read('../../shapefiles/DominguezChannel_Carson.shp')
d_channel <- read_sf('../../shapefiles/DominguezChannel_Carson.shp', layer = 'DominguezChannel_Carson')
d_channel <- st_transform(d_channel, CRS_UTM) # convert to UTM crs

# Get coordinates as columns
top_3_blk_daily_with_meteo <- top_3_blk_daily_with_meteo %>%
  st_as_sf(coords = c('longitude', 'latitude'), remove = F) %>%
  st_set_crs(CRS_LL) %>%
  st_transform(CRS_UTM) %>%
  mutate(mon_utm_x = sf::st_coordinates(.)[,1],
         mon_utm_y = sf::st_coordinates(.)[,2]) %>%
  st_drop_geometry()


# Compute static variables first
zipcode_data <- top_3_blk_daily_with_meteo %>%
  mutate(sf_loc = get_sf_loc(mon_utm_x, mon_utm_y),
         ll_loc = get_ll_loc(mon_utm_x, mon_utm_y))

zipcode_static_data <- zipcode_data %>%
  select(sf_loc, ll_loc, longitude, latitude) %>%
  distinct()

zipcode_static_data <- zipcode_static_data %>%
  mutate(dist_wrp = get_dist_wrp(sf_loc)$dist_wrp,
         MinDist = get_dist_ref(sf_loc),
         elevation = get_elevation(ll_loc),
         EVI = get_evi(sf_loc),
         capacity = get_dist_wrp(sf_loc)$capacity,
         dist_dc = apply(st_distance(sf_loc, d_channel), 1, min),
         angle_ref = get_angle_ref(sf_loc),
         angle_wrp = get_angle_wrp(sf_loc))

zipcode_static_data <- zipcode_static_data %>%
  rowwise() %>%
  mutate(inactive_2km = get_well_inactive(sf_loc)) %>%
  ungroup()

# Get zipcode for each blk
zipcode_static_data <- zipcode_static_data %>%
  left_join(top_3_blk_wo_meteo, join_by(longitude == INTPTLON, latitude == INTPTLAT)) %>%
  rename(zipcode = ZCTAA,
         block = BLOCKA,
         population = U7H001)
remove(top_3_blk_wo_meteo)

zipcode_data <- zipcode_data %>%
  left_join(zipcode_static_data)

# Compute dynamic time dependent variables
wind_diff <- abs(zipcode_data$angle_ref - zipcode_data$daily_wd)
wind_diff <- ifelse(wind_diff > 180, 360 - wind_diff, wind_diff)
zipcode_data$daily_downwind_ref <- as.integer(wind_diff <= 15)

wind_diff <- abs(zipcode_data$angle_wrp - zipcode_data$daily_wd)
wind_diff <- ifelse(wind_diff > 180, 360 - wind_diff, wind_diff)
zipcode_data$daily_downwind_wrp <- as.integer(wind_diff <= 15)

coord_month_well_prod <- zipcode_data %>%
  mutate(month_floor = floor_date(day, 'month')) %>%
  select(sf_loc, month_floor) %>%
  distinct()

coord_well <- coord_month_well_prod %>%
  select(sf_loc) %>%
  distinct() %>%
  rowwise() %>%
  mutate(api = list(active_well_location %>%
                  mutate(dist_to_loc = apply(st_distance(sf_loc, active_well_location), 2, min)) %>%
                  filter(dist_to_loc <= 2000) %>%
                  pull(`API/UWI`)))

coord_month_well_prod <- coord_month_well_prod %>%
  left_join(coord_well, join_by(sf_loc))

wells_monthly_prod <- coord_month_well_prod %>%
  rowwise() %>%
  mutate(well_prod_data = get_well_prod(api, month_floor)) %>%
  ungroup()

wells_monthly_prod <- wells_monthly_prod %>%
  mutate(active_2km = well_prod_data$active_2km,
         monthly_oil_2km = well_prod_data$monthly_oil_2km,
         monthly_gas_2km = well_prod_data$monthly_gas_2km) %>%
  select(-c(well_prod_data, api)) %>%
  mutate(yearmonth = format(month_floor, '%Y-%m'))

zipcode_data <- zipcode_data %>%
  left_join(wells_monthly_prod, join_by(sf_loc, yearmonth))

zipcode_data <- zipcode_data %>%
  rowwise() %>%
  mutate(num_odor_complaints = get_odor(zipcode, day))

zipcode_data <- zipcode_data %>%
  st_drop_geometry() %>%
  select(-c(sf_loc, ll_loc, month_floor, yearmonth))

# saveRDS(zipcode_data, 'zipcode_data.rds')
# write_csv(zipcode_data, 'zipcode_data.csv')
```

```{r}
zipcode_data <- readRDS('zipcode_data.rds')

zipcode_data <- zipcode_data %>%
  rename(ws_avg = daily_ws,
         wd_avg = daily_wd,
         avg_temp = daily_temp,
         avg_hum = daily_hum,
         precip = daily_precip)

zipcode_data<- zipcode_data %>%
                 mutate(disaster = if_else(year == 2021 & month %in% c('10', '11', '12'), 1, 0),
                        MinDist = 1/(MinDist^2),
                        dist_wrp = 1/(dist_wrp^2),
                        dist_dc = 1/(dist_dc^2),
                        year = as.character(year),
                        year_2023 = 0)

zipcode_data_mat <- fastDummies::dummy_cols(zipcode_data %>% 
                                              select(-c(zipcode, block, population, 
                                                        angle_wrp, angle_ref, day, 
                                                        latitude, longitude)),
                                 remove_selected_columns = TRUE)


zipcode_result <- zipcode_data %>%
  ungroup() %>%
  mutate(xgb_dis_ind_predict = predict(fit.xgb_da_log_h2s_dis_ind, newdata = zipcode_data_mat)) %>%
  mutate(daily_h2s_predict = exp(xgb_dis_ind_predict))

write_csv(zipcode_result, 'zipcode_result.csv')
```



