---
title: "Stepwise GAM based on GCV"
output: html_document
date: "2024-09-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# prepare stepwise function
# for this function, I will first have the set of features
# at each step, find the variable to add/remove that improves model the most
# using the GCV score (lower = better)
get_best_feature_forward <- function(response, used_features, unused_features, data) {
    print('Adding...')
    if (length(unused_features) > 0) {
      change_GCV_forward <- tibble(feature = unused_features, 
                           GCV_new = NA)
      for (feature in unused_features) {
        new_features <- c(used_features, feature)
        formula_feature_str <- paste(new_features, collapse = ' + ')
        formula_str <- paste(response, formula_feature_str, sep = ' ~ ')
        print(formula_str)
        formula <- as.formula(formula_str)
        
        gam_model <- gam(formula, data = data, method = 'GCV.Cp', select = TRUE)
        summary <- summary(gam_model)
        
        # get the GCV of new model
        GCV_new <- summary$sp.criterion[[1]]
        print(GCV_new)
        change_GCV_forward$GCV_new[change_GCV_forward$feature == feature] <- GCV_new
      }
      best_feature_forward <- change_GCV_forward[which(change_GCV_forward$GCV_new ==
                                                         min(change_GCV_forward$GCV_new)), ]
      best_feature_forward <- best_feature_forward[1, ]
    } else if (length(unused_features) == 0) {
      # no more feature to add so always prefer current model or backward
      best_feature_forward <- tibble(feature = 'FULLMODEL', GCV_new = Inf)
    } else {
      # no more feature to add in stepwise
      # backward should compare to last model
      best_feature_forward <- tibble(feature = NA, GCV_new = GCV)
    }
  return(best_feature_forward)
}

get_best_feature_backward <- function(response, used_features, unused_features, data) {
    print('Removing...')
    if (length(used_features) > 1) {
      change_GCV_backward <- tibble(feature = used_features, 
                                    GCV_new = NA)
      for (feature in used_features) {
        formula_feature_str <- paste(setdiff(used_features, feature), collapse = ' + ')
        formula_str <- paste(response, formula_feature_str, sep = ' ~ ')
        print(formula_str)
        formula <- as.formula(formula_str)
        
        gam_model <- gam(formula, data = data, method = 'GCV.Cp', select = TRUE)
        summary <- summary(gam_model)
        
        # get the GCV of new model
        GCV_new <- summary$sp.criterion[[1]]
        print(GCV_new)
        change_GCV_backward$GCV_new[change_GCV_backward$feature == feature] <- GCV_new
      }
      best_feature_backward <- change_GCV_backward[which(change_GCV_backward$GCV_new ==
                                                           min(change_GCV_backward$GCV_new)), ]
      best_feature_backward <- best_feature_backward[1, ]
    } else if (length(used_features) == 1) {
      # only one feature left to remove, which gives intercept model
        formula_str <- paste(response, '1', sep = ' ~ ')

        print(formula_str)
        formula <- as.formula(formula_str)
        
        gam_model <- gam(formula, data = data, method = 'GCV.Cp', select = TRUE)
        summary <- summary(gam_model)
        
        # get the GCV of new model
        GCV_new <- summary$sp.criterion[[1]]
        print(GCV_new)
        best_feature_backward <- tibble(feature = 'Intercept', GCV_new = GCV_new)
    } else {
      # no feature to remove so always prefer last model or forward
       best_feature_backward <- tibble(feature = NA, GCV_new = Inf)
    }
  return(best_feature_backward)
}

get_init_gcv <- function(response, used_features, unused_features, data) {
  if (length(used_features) == 0) {used_features <- c('1')}
  formula_feature_str <- paste(used_features, collapse = ' + ')
  formula_str <- paste(response, formula_feature_str, sep = ' ~ ')
  formula <- as.formula(formula_str)
  
  # use select = TRUE to add penalty to null space (zero wiggliness)
  # so smooth term can be penalized to zero instead of linear
  gam_model <- gam(formula, data = data, method = 'GCV.Cp', select = TRUE)
  summary <- summary(gam_model)
  
  # get the GCV of init model
  GCV <- summary$sp.criterion[[1]]
  print(paste0('Starting GCV: ', GCV))
  return(GCV)
}

step_gam <- function(response, features, init_features, direction, data) {
  step_i <- 1
  convergence <- FALSE
  used_features <- init_features
  unused_features <- setdiff(features, init_features)
  
  GCV <- get_init_gcv(response, used_features, unused_features, data)
  
  step_summary <- setNames(c(GCV, features %in% used_features), c("GCV", features))
  step_summary <- as_tibble(t(step_summary))
  
  i <- 1
  # until we reach convergence (GCV no longer decreases)
  while (convergence == FALSE) {
    print(paste0('Currently at ',i, ' iteration...'))
    # forward selection
    if (direction %in% c('forward', 'stepwise')) {
      best_feature_forward <- get_best_feature_forward(response, used_features, 
                                                       unused_features, data)
    }
  
    # backward selection
    if (direction %in% c('backward', 'stepwise')) {
      best_feature_backward <- get_best_feature_backward(response, used_features, 
                                                         unused_features, data)
    }
    
    if (direction == 'forward') {
      # compare the best feature to add with current GCV
      if (best_feature_forward$GCV_new <= GCV) {
        # add this feature to used feature vector and remove from unused
        used_features <- append(used_features, best_feature_forward$feature)
        unused_features <- setdiff(unused_features, best_feature_forward$feature)
        GCV <- best_feature_forward$GCV_new # update GCV
      } else {
        convergence == TRUE
        break
      }
    } else if (direction == 'backward') {
      if (best_feature_backward$GCV_new <= GCV) {
        # if this is intercept model and adding anything won't improve the model
        if (best_feature_backward$feature == 'Intercept') {
          convergence == TRUE
        }
        # add this feature to unused feature vector and remove from used
        unused_features <- append(unused_features, best_feature_backward$feature)
        used_features <- setdiff(used_features, best_feature_backward$feature)
        GCV <- best_feature_backward$GCV_new # update GCV
      } else {
        convergence == TRUE
        break
      }
    } else if (direction == 'stepwise') {
      # for this, need compare both directions
      # choose direction/feature that decreases GCV the most
      if (best_feature_forward$GCV_new < best_feature_backward$GCV_new) {
        # if forward is better (lower GCV)
        if (best_feature_forward$GCV_new <= GCV) {
          used_features <- append(used_features, best_feature_forward$feature)
          unused_features <- setdiff(unused_features, best_feature_forward$feature)
          GCV <- best_feature_forward$GCV_new
        } else {
          convergence == TRUE
        break
        }
      } else if (best_feature_forward$GCV_new == best_feature_backward$GCV_new) {
        # randomly choose step
        random_coin <- sample(c(1, 2), 1)
        if (random_coin == 1) {
          if (best_feature_forward$GCV_new < GCV) {
          # add this feature to used feature vector and remove from unused
            used_features <- append(used_features, best_feature_forward$feature)
            unused_features <- setdiff(unused_features, best_feature_forward$feature)
            GCV <- best_feature_forward$GCV_new # update GCV
          }
        } else {
            if (best_feature_backward$GCV_new < GCV) {
              # if this is intercept model and adding anything won't improve the model
              if (best_feature_backward$feature == 'Intercept') {
                convergence == TRUE
              }
              # add this feature to unused feature vector and remove from used
              unused_features <- append(unused_features, best_feature_backward$feature)
              used_features <- setdiff(used_features, best_feature_backward$feature)
              GCV <- best_feature_backward$GCV_new # update GCV
            }
          }
      } else {
        # else backward is better
        # if this new model gives better GCV than last model
        if (best_feature_backward$GCV_new <= GCV) {
          # if this is intercept model and adding anything won't improve the model
          if (best_feature_backward$feature == 'Intercept') {
            convergence == TRUE
          }
          # add this feature to unused feature vector and remove from used
          unused_features <- append(unused_features, best_feature_backward$feature)
          used_features <- setdiff(used_features, best_feature_backward$feature)
          GCV <- best_feature_backward$GCV_new # update GCV
        } else {
          convergence == TRUE
          break
        }
      }
    }
    
    # update step summary
    new_step_summary <- setNames(c(GCV, rep(TRUE, length(used_features))), c("GCV", used_features))
    new_step_summary <- as_tibble(t(new_step_summary))
    step_summary <- bind_rows(step_summary, new_step_summary)
    
    i <- i + 1
  }
  step_summary[is.na(step_summary)] <- 0
  return(step_summary)
}
```

### Daily Avg
```{r}
# since feb 2022 stepwise
predictors_sincefeb2022 <- 
  c("s(as.numeric(month),bs='cc')", 'year', 'weekday', 'wd_avg', 'ws_avg', 
    'daily_downwind_ref', 'I(1/dist_wrp^2)', 'I(1/dist_ref^2)', 
    "s(I(mon_utm_x/10^3), I(mon_utm_y/10^3), bs='tp', k = 10)",
    "te(I(mon_utm_x/10^3), I(mon_utm_y/10^3), as.numeric(day), k=c(10,10),d=c(2,1),bs=c('tp','cc'))",
    'monthly_oil_2km', 'monthly_gas_2km', 'active_2km', 'inactive_2km', 
    'daily_downwind_wrp', 'elevation', 'EVI', 'num_odor_complaints', 'I(1/dist_dc^2)', 
    'closest_wrp_capacity', 'daily_temp', 'daily_hum', 'daily_precip')

data_sincefeb2022 <- daily_full %>% filter(day > '2022-01-31')

# da_step_gam_table_empty_init_sincefeb2022 <- 
#   step_gam('H2S_daily_avg', predictors_sincefeb2022, c(), 'stepwise', data_sincefeb2022)
# da_step_gam_table_full_init_sincefeb2022 <- 
#   step_gam('H2S_daily_avg', predictors_sincefeb2022, predictors_sincefeb2022, 'stepwise', data_sincefeb2022)
```

```{r}
# Disaster stepwise
predictors_dis <- 
  c("month", "weekday", "wd_avg", "ws_avg", "daily_downwind_ref", 
    "closest_wrp_capacity", "I(1/dist_wrp^2)", "I(1/dist_ref^2)", 
    "s(I(mon_utm_x/10^3), I(mon_utm_y/10^3), bs='tp', k = 10)", 
    "te(I(mon_utm_x/10^3), I(mon_utm_y/10^3),as.numeric(day), k=c(10,10),d=c(2,1),bs=c('tp','cc'))",
    "monthly_oil_2km", "monthly_gas_2km", "active_2km", "inactive_2km", 
    "daily_downwind_wrp", "elevation", "EVI", "num_odor_complaints", 
    "I(1/dist_dc^2)", "daily_temp", "daily_hum", "daily_precip")

data_dis <- daily_full %>% filter(year == '2021', month %in% c('10', '11', '12'))
da_step_gam_table_empty_init_dis3 <-
  step_gam('H2S_daily_avg', predictors_dis, c(), 'stepwise', data_dis)
# da_step_gam_table_full_init_dis <- 
#   step_gam('H2S_daily_avg', predictors_dis, predictors_dis, 'stepwise', data_dis)
```

```{r}
# Exclude disaster stepwise
predictors_excl_dis <- 
  c("s(as.numeric(month),bs='cc')", 'year', 'weekday', 'wd_avg', 'ws_avg', 
    'daily_downwind_ref', 'I(1/dist_wrp^2)', 'I(1/dist_ref^2)', 
    "s(I(mon_utm_x/10^3), I(mon_utm_y/10^3), bs='tp', k = 10)",
    "te(I(mon_utm_x/10^3), I(mon_utm_y/10^3), as.numeric(day), k=c(10,10),d=c(2,1),bs=c('tp','cc'))",
    'monthly_oil_2km', 'monthly_gas_2km', 'active_2km', 'inactive_2km', 
    'daily_downwind_wrp', 'elevation', 'EVI', 'num_odor_complaints',
    'I(1/dist_dc^2)', 'closest_wrp_capacity', 'daily_temp', 'daily_hum', 'daily_precip')

data_excl_dis <- daily_full %>% filter(!(year == '2021' & month %in% c('10', '11', '12')))
# da_step_gam_table_empty_init_excl_dis <- 
#   step_gam('H2S_daily_avg', predictors_excl_dis, c(), 'stepwise', data_excl_dis)
# da_step_gam_table_full_init_excl_dis <- 
#   step_gam('H2S_daily_avg', predictors_excl_dis, predictors_excl_dis, 'stepwise', data_excl_dis)
```

```{r}
# full with disaster indicator
predictors_dis_ind <- 
  c("s(as.numeric(month),bs='cc')", 'year', 'weekday', 'wd_avg', 'ws_avg', 
    'daily_downwind_ref', 'I(1/dist_wrp^2)', 'I(1/dist_ref^2)',
    "s(I(mon_utm_x/10^3), I(mon_utm_y/10^3), bs='tp', k = 10)",
    "te(I(mon_utm_x/10^3), I(mon_utm_y/10^3), as.numeric(day), k=c(10,10),d=c(2,1),bs=c('tp','cc'))",
    'monthly_oil_2km', 'monthly_gas_2km', 'active_2km', 'inactive_2km', 
    'daily_downwind_wrp', 'elevation', 'EVI', 'num_odor_complaints', 'I(1/dist_dc^2)', 
    'closest_wrp_capacity', 'daily_temp', 'daily_hum', 'daily_precip', 'disaster')

data_dis_ind <- daily_full %>% 
  mutate(disaster = 
           if_else(year == '2021', month %in% c('10', '11', '12'), 1, 0))
# da_step_gam_table_empty_init_dis_ind <- 
#   step_gam('H2S_daily_avg', predictors_dis_ind, c(), 'stepwise', data_dis_ind)
# da_step_gam_table_full_init_dis_ind <- 
#   step_gam('H2S_daily_avg', predictors_dis_ind, predictors_dis_ind, 'stepwise', data_dis_ind)
```

```{r}
# full without disaster indicator
predictors_full <- 
  c("s(as.numeric(month),bs='cc')", 'year', 'weekday', 'wd_avg', 'ws_avg', 
    'daily_downwind_ref', 'I(1/dist_wrp^2)', 'I(1/dist_ref^2)',
    "s(I(mon_utm_x/10^3), I(mon_utm_y/10^3), bs='tp', k = 10)",
    "te(I(mon_utm_x/10^3), I(mon_utm_y/10^3), as.numeric(day), k=c(10,10),d=c(2,1),bs=c('tp','cc'))",
    'monthly_oil_2km', 'monthly_gas_2km', 'active_2km', 'inactive_2km', 
    'daily_downwind_wrp', 'elevation', 'EVI', 'num_odor_complaints', 'I(1/dist_dc^2)', 
    'closest_wrp_capacity', 'daily_temp', 'daily_hum', 'daily_precip')

# da_step_gam_table_empty_init_full <- 
#   step_gam('H2S_daily_avg', predictors_full, c(), 'stepwise', daily_full)
# da_step_gam_table_full_init_full <- 
#   step_gam('H2S_daily_avg', predictors_full, predictors_full, 'stepwise', daily_full)
```


### Log Daily Avg
```{r}
# since feb 2022 stepwise
log_da_step_gam_table_empty_init_sincefeb2022 <- 
  step_gam('log(H2S_daily_avg)', predictors_sincefeb2022, c(), 'stepwise', data_sincefeb2022)
log_da_step_gam_table_full_init_sincefeb2022 <- 
  step_gam('log(H2S_daily_avg)', predictors_sincefeb2022, predictors_sincefeb2022, 'stepwise', data_sincefeb2022)
```

```{r}
# Disaster stepwise
log_da_step_gam_table_empty_init_dis <- 
  step_gam('log(H2S_daily_avg)', predictors_dis, c(), 'stepwise', data_dis)
log_da_step_gam_table_full_init_dis <- 
  step_gam('log(H2S_daily_avg)', predictors_dis, predictors_dis, 'stepwise', data_dis)
```

```{r}
# Exclude disaster stepwise
log_da_step_gam_table_empty_init_excl_dis <- 
  step_gam('log(H2S_daily_avg)', predictors_excl_dis, c(), 'stepwise', data_excl_dis)
log_da_step_gam_table_full_init_excl_dis <- 
  step_gam('log(H2S_daily_avg)', predictors_excl_dis, predictors_excl_dis, 'stepwise', data_excl_dis)
```

```{r}
# full with disaster indicator
log_da_step_gam_table_empty_init_dis_ind <- 
  step_gam('log(H2S_daily_avg)', predictors_dis_ind, c(), 'stepwise', data_dis_ind)
log_da_step_gam_table_full_init_dis_ind <- 
  step_gam('log(H2S_daily_avg)', predictors_dis_ind, predictors_dis_ind, 'stepwise', data_dis_ind)
```

```{r}
# full without disaster indicator
log_da_step_gam_table_empty_init_full <- 
  step_gam('log(H2S_daily_avg)', predictors_full, c(), 'stepwise', daily_full)
log_da_step_gam_table_full_init_full <- 
  step_gam('log(H2S_daily_avg)', predictors_full, predictors_full, 'stepwise', daily_full)
```

### Daily Max
```{r}
# since feb 2022 stepwise
dm_step_gam_table_empty_init_sincefeb2022 <- 
  step_gam('H2S_daily_max', predictors_sincefeb2022, c(), 'stepwise', data_sincefeb2022)
dm_step_gam_table_full_init_sincefeb2022 <- 
  step_gam('H2S_daily_max', predictors_sincefeb2022, predictors_sincefeb2022, 'stepwise', data_sincefeb2022)
```

```{r}
# Disaster stepwise
dm_step_gam_table_empty_init_dis <- 
  step_gam('H2S_daily_max', predictors_dis, c(), 'stepwise', data_dis)
dm_step_gam_table_full_init_dis <- 
  step_gam('H2S_daily_max', predictors_dis, predictors_dis, 'stepwise', data_dis)
```

```{r}
# Exclude disaster stepwise
dm_step_gam_table_empty_init_excl_dis <- 
  step_gam('H2S_daily_max', predictors_excl_dis, c(), 'stepwise', data_excl_dis)
dm_step_gam_table_full_init_excl_dis <- 
  step_gam('H2S_daily_max', predictors_excl_dis, predictors_excl_dis, 'stepwise', data_excl_dis)
```

```{r}
# full with disaster indicator
dm_step_gam_table_empty_init_dis_ind <- 
  step_gam('H2S_daily_max', predictors_dis_ind, c(), 'stepwise', data_dis_ind)
dm_step_gam_table_full_init_dis_ind <- 
  step_gam('H2S_daily_max', predictors_dis_ind, predictors_dis_ind, 'stepwise', data_dis_ind)
```

```{r}
# full without disaster indicator
dm_step_gam_table_empty_init_full <- 
  step_gam('H2S_daily_max', predictors_full, c(), 'stepwise', daily_full)
dm_step_gam_table_full_init_full <- 
  step_gam('H2S_daily_max', predictors_full, predictors_full, 'stepwise', daily_full)
```

### Log Daily Max
```{r}
# since feb 2022 stepwise
log_dm_step_gam_table_empty_init_sincefeb2022 <- 
  step_gam('log(H2S_daily_max)', predictors_sincefeb2022, c(), 'stepwise', data_sincefeb2022)
log_dm_step_gam_table_full_init_sincefeb2022 <- 
  step_gam('log(H2S_daily_max)', predictors_sincefeb2022, predictors_sincefeb2022, 'stepwise', data_sincefeb2022)
```

```{r}
# Disaster stepwise
log_dm_step_gam_table_empty_init_dis <- 
  step_gam('log(H2S_daily_max)', predictors_dis, c(), 'stepwise', data_dis)
log_dm_step_gam_table_full_init_dis <- 
  step_gam('log(H2S_daily_max)', predictors_dis, predictors_dis, 'stepwise', data_dis)
```

```{r}
# Exclude disaster stepwise
log_dm_step_gam_table_empty_init_excl_dis <- 
  step_gam('log(H2S_daily_max)', predictors_excl_dis, c(), 'stepwise', data_excl_dis)
log_dm_step_gam_table_full_init_excl_dis <- 
  step_gam('log(H2S_daily_max)', predictors_excl_dis, predictors_excl_dis, 'stepwise', data_excl_dis)
```

```{r}
# full with disaster indicator
log_dm_step_gam_table_empty_init_dis_ind <- 
  step_gam('log(H2S_daily_max)', predictors_dis_ind, c(), 'stepwise', data_dis_ind)
log_dm_step_gam_table_full_init_dis_ind <- 
  step_gam('log(H2S_daily_max)', predictors_dis_ind, predictors_dis_ind, 'stepwise', data_dis_ind)
```

```{r}
# full without disaster indicator
log_dm_step_gam_table_empty_init_full <- 
  step_gam('log(H2S_daily_max)', predictors_full, c(), 'stepwise', daily_full)
log_dm_step_gam_table_full_init_full <- 
  step_gam('log(H2S_daily_max)', predictors_full, predictors_full, 'stepwise', daily_full)
```
